In [1]:
import torch
import numpy as np
import os


In [ ]:
import sys
sys.path.append('../')
import eval
import models

In [ ]:
%cd
%cd sinr/
%ls

/Users/filipdorm
/Users/filipdorm/sinr
LICENSE                       paths.json
README.md                     pretrained_models/
__pycache__/                  requirements.txt
data/                         setup.py
datasets.py                   train.py
eval.py                       train_and_evaluate_models.py
losses.py                     utils.py
models.py                     viz_ica.py
my_experiments/               viz_map.py
other_data/                   web_app/
output/


In [ ]:
# load model
train_params = torch.load('./pretrained_models/model_an_full_input_enc_sin_cos_hard_cap_num_per_class_1000.pt', map_location='cpu')
train_params['experiment_name'] = "model_an_full_input_enc_sin_cos_hard_cap_num_per_class_1000.pt"
model = models.get_model(train_params['params'])
model.load_state_dict(train_params['state_dict'], strict=True)
model = model.to('cpu')
model.eval()

ResidualFCNet(
  (class_emb): Linear(in_features=256, out_features=47375, bias=False)
  (feats): Sequential(
    (0): Linear(in_features=4, out_features=256, bias=True)
    (1): ReLU(inplace=True)
    (2): ResLayer(
      (nonlin1): ReLU(inplace=True)
      (nonlin2): ReLU(inplace=True)
      (dropout1): Dropout(p=0.5, inplace=False)
      (w1): Linear(in_features=256, out_features=256, bias=True)
      (w2): Linear(in_features=256, out_features=256, bias=True)
    )
    (3): ResLayer(
      (nonlin1): ReLU(inplace=True)
      (nonlin2): ReLU(inplace=True)
      (dropout1): Dropout(p=0.5, inplace=False)
      (w1): Linear(in_features=256, out_features=256, bias=True)
      (w2): Linear(in_features=256, out_features=256, bias=True)
    )
    (4): ResLayer(
      (nonlin1): ReLU(inplace=True)
      (nonlin2): ReLU(inplace=True)
      (dropout1): Dropout(p=0.5, inplace=False)
      (w1): Linear(in_features=256, out_features=256, bias=True)
      (w2): Linear(in_features=256, out_features=

In [ ]:
for eval_type in ['iucn']:
    eval_params = {}
    eval_params['exp_base'] = './pretrained_models'
    eval_params['experiment_name'] = train_params['experiment_name']
    eval_params['eval_type'] = eval_type
    if eval_type == 'iucn':
        eval_params['device'] = torch.device('cpu') # for memory reasons
    cur_results = eval.launch_eval_run(eval_params)
    np.save(os.path.join(eval_params['exp_base'], train_params['experiment_name'], f'results_{eval_type}.npy'), cur_results)


iucn
[[-29.992083 -34.167377 -26.67738  ... -29.583178 -27.599483 -30.873058]
 [-44.176468 -46.45711  -38.729893 ... -37.081287 -42.738182 -50.04854 ]
 [-41.3692   -43.147087 -36.040638 ... -34.645435 -39.429    -46.498325]
 ...
 [-39.88031  -52.564144 -42.476112 ... -50.427765 -37.361618 -38.415573]
 [-32.01905  -40.4126   -32.853275 ... -40.309063 -31.736357 -33.205116]
 [-35.124306 -47.171913 -38.19304  ... -46.70177  -33.557777 -34.322174]]


: 