notebook for evaluating what is done in calculate_f1_score.ipynb

In [19]:
import numpy as np

In [20]:
per_species_f1 = np.load('f1_scores.npy')

In [21]:
per_species_f1

array([[0.57711213, 0.75326381, 0.78050542, 0.77300104, 0.34940913],
       [0.38676204, 0.55916507, 0.59488004, 0.35535725, 0.26022254],
       [0.41555203, 0.5408408 , 0.55923005, 0.34323308, 0.00313557],
       ...,
       [0.29200766, 0.42108101, 0.48481928, 0.58480794, 0.69601677],
       [0.23578363, 0.29101284, 0.33355394, 0.42377756, 0.66005946],
       [0.03523573, 0.08290155, 0.12409514, 0.15343915, 0.17618271]])

In [22]:
per_species_f1[0,:]

array([0.57711213, 0.75326381, 0.78050542, 0.77300104, 0.34940913])

In [23]:
per_species_f1.mean(axis=0)

array([0.45746226, 0.53384108, 0.54954759, 0.52214561, 0.40272303])

In [24]:
per_species_f1.std(axis=0)

array([0.21622995, 0.21285718, 0.20697968, 0.20874241, 0.23972598])